config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users 

 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
 
  resources :fbpages, only: [:index]

  resources :users, only: [:show, :index]
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    
  end
  
  resources :likes, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 15 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts, dependent: :destroy
  has_many :likes ,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?


    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
         end


        def after_sign_in_path_for(resource)
            fbpages_path
        end

        def after_sign_out_path_for(resource)
            root_url
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController



    # The second one works
    # def create

    #     @post = Post.find(params[:post_id])
    #     @comment = @post.comments.create(comment_params)
    #     redirect_to fbpages_path(@post)

    # end

    # private
    # def comment_params
    #   params.require(:comment).permit(:commenter, :body)
    # end


    def create 
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new(comment_params)
        if @comment.save
            redirect_to fbpages_path,
            notice: "Comment Added"
        else
            redirect_to fbpages_path
        end
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to fbpages_path, status: :see_other,
        alert: "Comment Deleted"
    end

     private
    def comment_params
      params.require(:comment).permit(:body, :post_id, :name)
    end

end

app/controllers/fbpages_controller.rb
class FbpagesController < ApplicationController
    before_action :authenticate_user!
    def index
       @posts = Post.all
       @comment = Comment.all
       @likes = Like.all
      
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
    def index
        # render
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


    def create
        @post = Post.find(params[:post_id])
        @user = User.find(params[:user_id])
        @like = Like.new(like_params)
        if @like.save
            redirect_to fbpages_path
        else
        
        end
    end

    def destroy
        @user = User.find(params[:id])
        @post = Post.find_by(like_params)
        @like = @user.likes.find(params[:id])
        @like.destroy!
        @post.user.likes.destroy
        redirect_to fbpages_path, status: :see_other
    end


    private

    def like_params
        params.permit(:user_id, :post_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user!

    def index
        # @posts = Post.all
    end

    def new
        # @user = User.find[:id]
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if @post.save
            redirect_to fbpages_path, notice: "Post Added"
        else
            render new
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        @user = current_user.id
        if @post.update(post_params)
            redirect_to fbpages_path, notice: "Successfully Updated"
          else
            render :edit, status: :unprocessable_entity
          end
    end


    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        # @user = current_user.id
        redirect_to fbpages_path, status: :see_other, notice: "Post Deleted"
      end

    private
    def post_params
        params.require(:post).permit(:title, :body, :user_id)
    end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
        
    end

    def show
        @posts = Post.all
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fbpages_helper.rb
module FbpagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comments-wrapper">
    <%if current_user.name == comment.name%>    
        <strong>
            <%=comment.name %>:
        </strong> <i><%= comment.body %></i>
        <div class="">
            <%= link_to "Delete", [comment.post, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>

                                
        </div>
    <% else%>
    <strong>
            <%=comment.name %>:
        </strong> <i><%= comment.body %></i>
    <%end%>
</div>

app/views/fbpages/index.html.erb
<% if user_signed_in?%>

    <div class="container">
        <%  @posts.each do |post|%>
            <div class="post-wrapper">
                <div class= "post-header">
                    <h1><%= post.title%></h1>
                    <h5><%= post.created_at%></h5>
                    <p><%= post.user.email%></p>
                </div>
                <div class="post-body">
                    <p>
                        <%= post.body%>
                    </p>
                </div>
                <% if post.user.id == current_user.id%>
                    <div class="post-btn">
                        <div class="post-btn-top-right">
                            <%= link_to "Edit", edit_post_path(post)%>
                            <%= link_to "Delete Post", post_path(post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
                        </div>
                    </div>
                <%end%>
                  <div class="post-btn">
                    <h5>React</h5>
                        <div class="react">
                          <%#if @likes.present? && current_user.posts ==  post%>
                            <% if post.likes.count <= 0 %>
                              <%#if post.user.id == current_user.id%>
                                  <div class="reacts">
                                    <% if post.likes.count <= 0%>
                                      <%= link_to "👍", likes_path(:post_id => post, :user_id => current_user), data: { turbo_method: :post}%>
                                      <%else%>
                                       <%= link_to "👎", like_path(current_user),
                                      data: { turbo_method: :delete,
                                              }%>
                                    <% end%>
                                  </div>
                                <%else%>
                                  <div class="reacts">
                                    <% if post.likes.count >= 1%>
                                      <%= link_to "👎", like_path(current_user) ,
                                      data: { turbo_method: :delete,
                                              }%>
                                      <%else%>
                                      <%= link_to "👍", likes_path(:post_id => post, :user_id => current_user), data: { turbo_method: :post}%>
                                    <% end%>
                                  </div>
                              <%#end%>
                            <%end%>
                          <%#end%>
                        </div>
                        <div class="likes">
                            <%= post.likes.count%>
                        </div>
                  </div>

                <div class="comment-wrapper">
                    <strong>Comments: </strong>
                      <%= render post.comments %>
                        <div class="comment-form">
                          <p>Add Comment here:</p>
                            <%= form_with model:[ post, post.comments.build ] do |f| %>
                                <p>
                                    <%= f.text_area :body %>
                                    <%= f.hidden_field :name, value: current_user.name%>
                                </p>
                                <p>
                                    <%= f.submit class: "comment-submit" %>
                                </p>
                            <% end%>
                        </div>
                </div>
            </div>
        <% end%>
    </div>

<% else%>

  <h1>Welcome to the homepage!</h1><br>


<% end%>

app/views/layouts/_header.html.erb
<header>


     <nav class="navbar">
        <a class="navbar-brand" href="#">Facebook</a>
        <% if user_signed_in?%>
            <ul class="navbar-nav">
                <li class="nav-item">
                     <%= link_to "Home", fbpages_path%>
                </li>
                <li class="nav-item">
                    <%= link_to "New Post", new_post_path%>
                </li>
                <li class="nav-item">
                    <%= link_to "Friends", users_path%>
                </li>
                  <li class="nav-item">
                    <%= link_to "Sign_out", destroy_user_session_path,
                                            data: { turbo_method: :delete}%>
                </li> 
                <li class="nav-item">
                    <%= link_to current_user.name, current_user, class: "usersname"%>
                </li>
              
            </ul>
        <%end%>
    </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FbClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags%>
  </head>

  <body>
    <%= render "layouts/header"%>
    <main>
      <div class = "container-fluid">
          <div class="notice-wrapper">
          <p class="notice"><%= notice %></p>
          </div>
          <div class="alert-wrapper">
            <p class="alert"><%= alert %></p>
          </div>
      </div>
       <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-container">
    <%= form_with(model: @post, local: true) do |f| %>
            <%= f.label :title%><br>
            <%= f.text_field :title, autofocus: true, autocomplete: "title"%><br>

            <%= f.label :body%><br>
            <%= f.text_area :body, autofocus: true, autocomplete: "body"%><br>

            <%= f.submit "Submit", class: "btn btn-primary btn-block"%>
    <% end %>
</div>

app/views/posts/edit.html.erb
<h3 class="center">Edit Post<h3>
  <%= render "form"%>

app/views/posts/new.html.erb
        <h3 class="center">Create New Post</h3>
    <%= render "form"%>

app/views/users/index.html.erb
<div class="container">

    <div class="user-friend-wrapper">

    <h1>No friend request and friends yet.</h1> 

    </div>


</div>

app/views/users/show.html.erb
<div class="container">

   
    <div class = "user-profile">

        <div class="user-profile-pic">
            <div class="avatar">
                <img src="#" alt="profile">
            </div>
            <%= link_to "Edit Profile Image"%>
        </div>

        <div class="user-profile-info">
            <div class="user-profile-infos">
                <strong>Name:</strong> <%= current_user.name%>
            </div>
            <div class="user-profile-infos">
                <strong>Email:</strong> <%= current_user.email%>
                 
            </div>
             <div class="user-profile-infos">
                <strong>Post Likes:</strong> 
                   <%= current_user.likes.count%>
            </div>
        </div>
        <div class="profile-btn">
            <%= link_to "Edit Profile", edit_user_registration_path%>
        </div>
    </div>

    <div class="user-posts">
      <%  @posts.each do |post|%>
        <% if post.user.id == current_user.id%>
            <div class="post-wrapper">
                <div class= "post-header">
                    <h1><%= post.title%></h1>
                    <h5><%= post.created_at%></h5>
                    <p><%= post.user.email%></p>
                </div>
                <div class="post-body">
                    <%= post.body%>
                </div>
                <div class="profile-btn">
                    <%= link_to "Edit Profile", edit_post_path(post.id)%>
                    <%= link_to "Delete Post", post_path(post.id), data:{
                                               turbo_method: :delete,
                                               turbo_confirm: "Are you sure?"
                    }%>
                </div>
            </div>
        <%end%>
      <%end%>
    </div>
</div>